module.exports = {
    konfigTemp:
    [
        {id: 1, rodzaj: 'ogrzewanie', idTempWy : 0, idTempNast : 0, idGrzanie : 16943, idGrzanieSter : 16543, nazwa : 'Salon kanałowy', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'calyDom'},
        {id: 2, rodzaj: 'ogrzewanie', idTempWy : 17203, idTempNast : 16397, idGrzanie : 16942, idGrzanieSter : 16542, nazwa : 'Salon', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 3, rodzaj: 'ogrzewanie', idTempWy : 17201, idTempNast : 16393, idGrzanie : 16944, idGrzanieSter : 16544, nazwa : 'Gabinet Gosi', idLokalu : 3, nazwaLokalu : 'Gabinet Gosi', poziom : 'parter'},
        {id: 4, rodzaj: 'ogrzewanie', idTempWy : 17205, idTempNast : 16395, idGrzanie : 16941, idGrzanieSter : 16541, nazwa : 'WC', idLokalu : 4, nazwaLokalu : 'WC', poziom : 'parter'},
        {id: 5, rodzaj: 'ogrzewanie', idTempWy : 17199, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Wiatrołap', idLokalu : 5, nazwaLokalu : 'Wiatrołap', poziom : 'parter'},
        {id: 6, rodzaj: 'ogrzewanie', idTempWy : 17197, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Garaż', idLokalu : 7, nazwaLokalu : 'Garaż', poziom : 'calyDom'},
        {id: 7, rodzaj: 'ogrzewanie', idTempWy : 0, idTempNast : 0, idGrzanie : 16945, idGrzanieSter : 16545, nazwa : 'Pom. Gospodarcze', idLokalu : 8, nazwaLokalu : 'Pom. Gospodarcze', poziom : 'calyDom'},
        {id: 8, rodzaj: 'ogrzewanie', idTempWy : 17209, idTempNast : 16405, idGrzanie : 16949, idGrzanieSter : 16549, nazwa : 'Sypialnia', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'pietro'},
        {id: 9, rodzaj: 'ogrzewanie', idTempWy : 17213, idTempNast : 16401, idGrzanie : 16947, idGrzanieSter : 16547, nazwa : 'Gabinet Radka', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'pietro'},
        {id: 10, rodzaj: 'ogrzewanie', idTempWy : 17215, idTempNast : 16399, idGrzanie : 16946, idGrzanieSter : 16546, nazwa : 'Pokój Maćka', idLokalu : 11, nazwaLokalu : 'Pokój Maćka', poziom : 'pietro'},
        {id: 11, rodzaj: 'ogrzewanie', idTempWy : 17217, idTempNast : 16407, idGrzanie : 16950, idGrzanieSter : 16550, nazwa : 'Pokój gościnny', idLokalu : 12, nazwaLokalu : 'Pokój gościnny', poziom : 'pietro'},
        {id: 12, rodzaj: 'ogrzewanie', idTempWy : 17211, idTempNast : 16403, idGrzanie : 16948, idGrzanieSter : 16548, nazwa : 'Łazienka', idLokalu : 13, nazwaLokalu : 'Łazienka', poziom : 'pietro'},
        {id: 13, rodzaj: 'ogrzewanie', idTempWy : 17207, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Korytarz', idLokalu : 14, nazwaLokalu : 'Korytarz', poziom : 'pietro'},
        {id: 14, rodzaj: 'ogrzewanie', idTempWy : 17219, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Pralnia', idLokalu : 15, nazwaLokalu : 'Pralnia', poziom : 'pietro'},
        {id: 15, rodzaj: 'ogrzewanie', idTempWy : 17221, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Zewnetrzna', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 16, rodzaj: 'ogrzewanie', idTempWy : 17223, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Wymiennik', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 17, rodzaj: 'ogrzewanie', idTempWy : 17225, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Nawiew', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 18, rodzaj: 'ogrzewanie', idTempWy : 17227, idTempNast : 0, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Wyciag', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 19, rodzaj: 'ogrzewanie', idTempWy : 0, idTempNast : 16389, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'Delta', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 20, rodzaj: 'ogrzewanie', idTempWy : 0, idTempNast : 16391, idGrzanie : 0, idGrzanieSter : 0, nazwa : 'eko', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
    ], 
   konfig: 
   [
        {id: 1, rodzaj: 'swiatlo', idWy : 16911, idWySter : 16511, nazwa : 'Jadalnia kinkiet', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 2, rodzaj: 'swiatlo', idWy : 16912, idWySter : 16512, nazwa : 'Kinkiet słup', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 3, rodzaj: 'swiatlo', idWy : 16936, idWySter : 16536, nazwa : 'Nad ekranem', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 4, rodzaj: 'swiatlo', idWy : 16913, idWySter : 16513, nazwa : 'Zyrandor dol', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 5, rodzaj: 'swiatlo', idWy : 16908, idWySter : 16508, nazwa : 'Zyrandor gora', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 6, rodzaj: 'swiatlo', idWy : 16905, idWySter : 16505, nazwa : 'Barek', idLokalu : 2, nazwaLokalu : 'Kuchnia', poziom : 'parter'},
        {id: 7, rodzaj: 'swiatlo', idWy : 16906, idWySter : 16506, nazwa : 'Sufit', idLokalu : 2, nazwaLokalu : 'Kuchnia', poziom : 'parter'},
        {id: 8, rodzaj: 'swiatlo', idWy : 16907, idWySter : 16507, nazwa : 'sufit led', idLokalu : 2, nazwaLokalu : 'Kuchnia', poziom : 'parter'},
        {id: 9, rodzaj: 'swiatlo', idWy : 16901, idWySter : 16501, nazwa : 'Sufit', idLokalu : 3, nazwaLokalu : 'Gabinet Gosi', poziom : 'parter'},
        {id: 10, rodzaj: 'swiatlo', idWy : 16914, idWySter : 16514, nazwa : 'Sufit', idLokalu : 4, nazwaLokalu : 'WC', poziom : 'parter'},
        {id: 11, rodzaj: 'swiatlo', idWy : 16903, idWySter : 16503, nazwa : 'Sufit', idLokalu : 5, nazwaLokalu : 'Wiatrołap', poziom : 'parter'},
        {id: 12, rodzaj: 'swiatlo', idWy : 16904, idWySter : 16504, nazwa : 'Sufit', idLokalu : 6, nazwaLokalu : 'Korytarz', poziom : 'parter'},
        {id: 13, rodzaj: 'swiatlo', idWy : 16937, idWySter : 16537, nazwa : 'Kinkiet', idLokalu : 7, nazwaLokalu : 'Garaż', poziom : 'parter'},
        {id: 14, rodzaj: 'swiatlo', idWy : 16930, idWySter : 16530, nazwa : 'Sufit', idLokalu : 7, nazwaLokalu : 'Garaż', poziom : 'parter'},
        {id: 15, rodzaj: 'swiatlo', idWy : 16920, idWySter : 16520, nazwa : 'Kinkiet', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'pietro'},
        {id: 16, rodzaj: 'swiatlo', idWy : 16919, idWySter : 16519, nazwa : 'Sufit', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'pietro'},
        {id: 17, rodzaj: 'swiatlo', idWy : 16928, idWySter : 16528, nazwa : 'Taras przy sypialni', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'pietro'},
        {id: 18, rodzaj: 'swiatlo', idWy : 16917, idWySter : 16517, nazwa : 'Sufit', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'pietro'},
        {id: 19, rodzaj: 'swiatlo', idWy : 16918, idWySter : 16518, nazwa : 'Kinkiet', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'pietro'},
        {id: 20, rodzaj: 'swiatlo', idWy : 16916, idWySter : 16516, nazwa : 'Balkon pok Radka', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'pietro'},
        {id: 21, rodzaj: 'swiatlo', idWy : 16923, idWySter : 16523, nazwa : 'Sufit', idLokalu : 11, nazwaLokalu : 'Pokój Maćka', poziom : 'pietro'},
        {id: 22, rodzaj: 'swiatlo', idWy : 16924, idWySter : 16524, nazwa : 'Kinkiet', idLokalu : 11, nazwaLokalu : 'Pokój Maćka', poziom : 'pietro'},
        {id: 23, rodzaj: 'swiatlo', idWy : 16929, idWySter : 16529, nazwa : 'Sufit', idLokalu : 12, nazwaLokalu : 'Pokój gościnny', poziom : 'pietro'},
        {id: 24, rodzaj: 'swiatlo', idWy : 16921, idWySter : 16521, nazwa : 'Sufit lustro', idLokalu : 13, nazwaLokalu : 'Łazienka', poziom : 'pietro'},
        {id: 25, rodzaj: 'swiatlo', idWy : 16922, idWySter : 16522, nazwa : 'Sufit wanna', idLokalu : 13, nazwaLokalu : 'Łazienka', poziom : 'pietro'},
        {id: 26, rodzaj: 'swiatlo', idWy : 16933, idWySter : 16533, nazwa : 'Sufit', idLokalu : 14, nazwaLokalu : 'Korytarz', poziom : 'pietro'},
        {id: 27, rodzaj: 'swiatlo', idWy : 16932, idWySter : 16532, nazwa : 'Sufit szafa', idLokalu : 14, nazwaLokalu : 'Korytarz', poziom : 'pietro'},
        {id: 28, rodzaj: 'swiatlo', idWy : 16925, idWySter : 16525, nazwa : 'Stopnie', idLokalu : 16, nazwaLokalu : 'Schody', poziom : 'pietro'},
        {id: 29, rodzaj: 'swiatlo', idWy : 16915, idWySter : 16515, nazwa : 'Sufit', idLokalu : 16, nazwaLokalu : 'Schody', poziom : 'pietro'},
        {id: 30, rodzaj: 'swiatlo', idWy : 16926, idWySter : 16526, nazwa : 'Nad garażem', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 31, rodzaj: 'swiatlo', idWy : 16934, idWySter : 16534, nazwa : 'Podbitka przód i boki', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 32, rodzaj: 'swiatlo', idWy : 16935, idWySter : 16535, nazwa : 'Podbitka tył', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 33, rodzaj: 'swiatlo', idWy : 16927, idWySter : 16527, nazwa : 'Przed wejsciem', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 34, rodzaj: 'swiatlo', idWy : 16909, idWySter : 16509, nazwa : 'Taras od ogrodu', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 35, rodzaj: 'swiatlo', idWy : 16910, idWySter : 16510, nazwa : 'Taras południe', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 36, rodzaj: 'czujka', idWy : 17102, idWySter : 0, nazwa : 'K_Okno_taras', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 37, rodzaj: 'czujka', idWy : 17118, idWySter : 0, nazwa : 'PIR_Salon', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 38, rodzaj: 'czujka', idWy : 17103, idWySter : 0, nazwa : 'K_Kuchnia', idLokalu : 2, nazwaLokalu : 'Kuchnia', poziom : 'parter'},
        {id: 39, rodzaj: 'czujka', idWy : 17119, idWySter : 0, nazwa : 'PIR_Kuchnia', idLokalu : 2, nazwaLokalu : 'Kuchnia', poziom : 'parter'},
        {id: 40, rodzaj: 'czujka', idWy : 17121, idWySter : 0, nazwa : 'PIR_Gabinet_dol', idLokalu : 3, nazwaLokalu : 'Gabinet Gosi', poziom : 'parter'},
        {id: 41, rodzaj: 'czujka', idWy : 17122, idWySter : 0, nazwa : 'PIR_Wiatrolap', idLokalu : 5, nazwaLokalu : 'Wiatrołap', poziom : 'parter'},
        {id: 42, rodzaj: 'czujka', idWy : 17120, idWySter : 0, nazwa : 'PIR_Korytarz_dol', idLokalu : 6, nazwaLokalu : 'Korytarz', poziom : 'parter'},
        {id: 43, rodzaj: 'czujka', idWy : 17116, idWySter : 0, nazwa : 'PIR_Garaz', idLokalu : 7, nazwaLokalu : 'Garaż', poziom : 'parter'},
        {id: 44, rodzaj: 'czujka', idWy : 17117, idWySter : 0, nazwa : 'PIR_Kotlownia', idLokalu : 8, nazwaLokalu : 'Pom. Gospodarcze', poziom : 'parter'},
        {id: 45, rodzaj: 'czujka', idWy : 17107, idWySter : 0, nazwa : 'K_Sypialnia_taras', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'pietro'},
        {id: 46, rodzaj: 'czujka', idWy : 17129, idWySter : 0, nazwa : 'PIR_Sypialnia', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'pietro'},
        {id: 47, rodzaj: 'czujka', idWy : 17109, idWySter : 0, nazwa : 'K_Okno_gabinet_gora', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'pietro'},
        {id: 48, rodzaj: 'czujka', idWy : 17126, idWySter : 0, nazwa : 'PIR_Gabinet_gora', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'pietro'},
        {id: 49, rodzaj: 'czujka', idWy : 17110, idWySter : 0, nazwa : 'K_Okno_pokoj_Macka', idLokalu : 11, nazwaLokalu : 'Pokój Maćka', poziom : 'pietro'},
        {id: 50, rodzaj: 'czujka', idWy : 17128, idWySter : 0, nazwa : 'PIR_Pokoj_Macka', idLokalu : 11, nazwaLokalu : 'Pokój Maćka', poziom : 'pietro'},
        {id: 51, rodzaj: 'czujka', idWy : 17112, idWySter : 0, nazwa : 'K_Okno_pokoj_goscinny', idLokalu : 12, nazwaLokalu : 'Pokój gościnny', poziom : 'pietro'},
        {id: 52, rodzaj: 'czujka', idWy : 17127, idWySter : 0, nazwa : 'PIR_Pokoj_goscinny', idLokalu : 12, nazwaLokalu : 'Pokój gościnny', poziom : 'pietro'},
        {id: 53, rodzaj: 'czujka', idWy : 17108, idWySter : 0, nazwa : 'K_Lazienka_gora', idLokalu : 13, nazwaLokalu : 'Łazienka', poziom : 'pietro'},
        {id: 54, rodzaj: 'czujka', idWy : 17124, idWySter : 0, nazwa : 'PIR_Korytarz_gora', idLokalu : 14, nazwaLokalu : 'Korytarz', poziom : 'pietro'},
        {id: 55, rodzaj: 'czujka', idWy : 17111, idWySter : 0, nazwa : 'K_Okno_pralnia', idLokalu : 15, nazwaLokalu : 'Pralnia', poziom : 'pietro'},
        {id: 56, rodzaj: 'czujka', idWy : 17125, idWySter : 0, nazwa : 'PIR_Pralnia', idLokalu : 15, nazwaLokalu : 'Pralnia', poziom : 'pietro'},
        {id: 57, rodzaj: 'czujka', idWy : 17106, idWySter : 0, nazwa : 'K_Okno_klatka', idLokalu : 16, nazwaLokalu : 'Schody', poziom : 'pietro'},
        {id: 58, rodzaj: 'czujka', idWy : 17123, idWySter : 0, nazwa : 'PIR_Klatka_schodowa', idLokalu : 16, nazwaLokalu : 'Schody', poziom : 'pietro'},
        {id: 59, rodzaj: 'czujka', idWy : 17101, idWySter : 0, nazwa : 'K_Wyjscie_ogrod', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 60, rodzaj: 'czujka', idWy : 17135, idWySter : 0, nazwa : 'A_Dym', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 61, rodzaj: 'czujka', idWy : 17134, idWySter : 0, nazwa : 'A_Gaz', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 62, rodzaj: 'czujka', idWy : 17100, idWySter : 0, nazwa : 'K_1', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 63, rodzaj: 'czujka', idWy : 17113, idWySter : 0, nazwa : 'K_14', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 64, rodzaj: 'czujka', idWy : 17104, idWySter : 0, nazwa : 'K_5', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 65, rodzaj: 'czujka', idWy : 17105, idWySter : 0, nazwa : 'K_6', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 66, rodzaj: 'czujka', idWy : 17136, idWySter : 0, nazwa : 'K_Wejscie_glowne', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 67, rodzaj: 'czujka', idWy : 17130, idWySter : 0, nazwa : 'PIR', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 68, rodzaj: 'czujka', idWy : 17131, idWySter : 0, nazwa : 'PIR', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 69, rodzaj: 'czujka', idWy : 17132, idWySter : 0, nazwa : 'PIR', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 70, rodzaj: 'czujka', idWy : 17133, idWySter : 0, nazwa : 'PIR', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 71, rodzaj: 'czujka', idWy : 17115, idWySter : 0, nazwa : 'S_Centrali', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 72, rodzaj: 'czujka', idWy : 17114, idWySter : 0, nazwa : 'S_Syreny', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 73, rodzaj: 'sila', idWy : 16956, idWySter : 16556, nazwa : 'Sypialnia tv', idLokalu : 9, nazwaLokalu : 'Sypialnia', poziom : 'calyDom'},
        {id: 74, rodzaj: 'sila', idWy : 16957, idWySter : 16557, nazwa : 'Gabinet gora', idLokalu : 10, nazwaLokalu : 'Gabinet Radka', poziom : 'calyDom'},
        {id: 75, rodzaj: 'sila', idWy : 16955, idWySter : 16555, nazwa : 'Pok goscinny tv', idLokalu : 12, nazwaLokalu : 'Pokój gościnny', poziom : 'calyDom'},
        {id: 76, rodzaj: 'sila', idWy : 16953, idWySter : 16553, nazwa : 'Gniazdo zewn', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 77, rodzaj: 'sila', idWy : 16954, idWySter : 16554, nazwa : 'Taras gniazdo', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 78, rodzaj: 'sila', idWy : 16958, idWySter : 16558, nazwa : 'Balkon sypialni', idLokalu : 17, nazwaLokalu : 'Na zewnątrz', poziom : 'calyDom'},
        {id: 79, rodzaj: 'sumy', idWy : 16999, idWySter : 0, nazwa : 'swiatla', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 80, rodzaj: 'sumy', idWy : 17159, idWySter : 0, nazwa : 'czujki', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 81, rodzaj: 'ekran', idWy : 16962, idWySter : 16562, nazwa : 'ekran_d', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 82, rodzaj: 'ekran', idWy : 16961, idWySter : 16561, nazwa : 'ekran_g', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 83, rodzaj: 'ekran', idWy : 16990, idWySter : 16590, nazwa : 'ekran_poz', idLokalu : 1, nazwaLokalu : 'Salon', poziom : 'parter'},
        {id: 84, rodzaj: 'brink', idWy : 16938, idWySter : 16538, nazwa : 'zal_wyl', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 85, rodzaj: 'brink', idWy : 16939, idWySter : 16539, nazwa : '2bieg', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'},
        {id: 86, rodzaj: 'brink', idWy : 16940, idWySter : 16540, nazwa : '3bieg', idLokalu : 18, nazwaLokalu : 'Ogólne', poziom : 'calyDom'}
]
   
}